 ## Describe Data

In this project, we have to predict whether a patient is suffering from a heart attack or is likely to have a heart attack according to the medical information of a patient, which is fully described below?!





# Importing Libraries

In [3]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

## Load Data From CSV File


In [4]:
heart_data = pd.read_csv('Heart.csv')
heart_data.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [5]:
heart_data.dtypes
print(heart_data['oldpeak'].value_counts())

oldpeak
0.0    99
1.2    17
1.0    14
0.6    14
1.4    13
0.8    13
0.2    12
1.6    11
1.8    10
0.4     9
2.0     9
0.1     7
2.8     6
2.6     6
1.5     5
3.0     5
1.9     5
0.5     5
3.6     4
2.2     4
2.4     3
0.9     3
3.4     3
4.0     3
0.3     3
2.3     2
3.2     2
2.5     2
4.2     2
1.1     2
3.1     1
0.7     1
3.5     1
6.2     1
1.3     1
5.6     1
2.9     1
2.1     1
3.8     1
4.4     1
Name: count, dtype: int64


In [6]:
heart_data['oldpeak'].astype(np.int64)

0      2
1      3
2      1
3      0
4      0
      ..
298    0
299    1
300    3
301    1
302    0
Name: oldpeak, Length: 303, dtype: int64

In [7]:
feature_data = heart_data[['age','sex','cp','trtbps','chol','fbs','restecg','thalachh','exng','oldpeak','slp','caa','thall']]
X = np.asarray(feature_data)
X[0:5]

array([[ 63. ,   1. ,   3. , 145. , 233. ,   1. ,   0. , 150. ,   0. ,
          2.3,   0. ,   0. ,   1. ],
       [ 37. ,   1. ,   2. , 130. , 250. ,   0. ,   1. , 187. ,   0. ,
          3.5,   0. ,   0. ,   2. ],
       [ 41. ,   0. ,   1. , 130. , 204. ,   0. ,   0. , 172. ,   0. ,
          1.4,   2. ,   0. ,   2. ],
       [ 56. ,   1. ,   1. , 120. , 236. ,   0. ,   1. , 178. ,   0. ,
          0.8,   2. ,   0. ,   2. ],
       [ 57. ,   0. ,   0. , 120. , 354. ,   0. ,   1. , 163. ,   1. ,
          0.6,   2. ,   0. ,   2. ]])

In [8]:
heart_data['output'] = heart_data['output'].astype('int')
y = np.asarray(heart_data['output'])
y[0:5]

array([1, 1, 1, 1, 1])

# Train/Test dataset

### We split our dataset into train and test set:

In [9]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (242, 13) (242,)
Test set: (61, 13) (61,)


# Modeling (SVM with Scikit-learn)

In [10]:
from sklearn import svm
DH = svm.SVC(kernel='rbf')
DH.fit(X_train , y_train)

SVC()

### After being fitted, the model can then be used to predict new values:

In [11]:
yhat = DH.predict(X_test)
yhat[0:5]

array([1, 1, 1, 1, 0])

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

accuracy = accuracy_score(y_test, yhat)
precision = precision_score(y_test, yhat)
recall = recall_score(y_test, yhat)
f1 = f1_score(y_test, yhat)
confusion_mat = confusion_matrix(y_test, yhat)


print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:")
print(confusion_mat)


Accuracy: 0.6721311475409836
Precision: 0.6739130434782609
Recall: 0.8611111111111112
F1-score: 0.7560975609756099
Confusion Matrix:
[[10 15]
 [ 5 31]]


## Author

Abolfazl Shahri